-- Insert 30+ opportunities for Indonesian students and professionals

-- SCHOLARSHIPS (Beasiswa)
INSERT INTO scraped_content (title, description, category, content_type, deadline, registration_start_date, registration_end_date, organizer, location, requirements, contact_info, source_website, url, tags, is_manual) VALUES 

('Beasiswa LPDP S2 Luar Negeri', 'Beasiswa penuh untuk program magister di universitas terbaik dunia dengan dukungan biaya hidup dan penelitian', 'SCHOLARSHIP', 'scholarship', '2025-03-15'::timestamp, '2025-01-01'::timestamp, '2025-03-15'::timestamp, 'LPDP', 'Internasional', ARRAY['S1 terakreditasi A', 'IPK min 3.0', 'TOEFL/IELTS', 'Surat rekomendasi'], '{"email": "info@lpdp.kemenkeu.go.id", "phone": "021-1234567"}', 'https://lpdp.kemenkeu.go.id', 'https://lpdp.kemenkeu.go.id/beasiswa', ARRAY['beasiswa', 'luar negeri', 'S2', 'magister'], true),

('Beasiswa Unggulan Kemendikbud 2025', 'Program beasiswa untuk mahasiswa berprestasi tinggi melanjutkan studi S2/S3 dalam dan luar negeri', 'SCHOLARSHIP', 'scholarship', '2025-04-30'::timestamp, '2025-02-01'::timestamp, '2025-04-30'::timestamp, 'Kemendikbud', 'Indonesia & Luar Negeri', ARRAY['Mahasiswa aktif/fresh graduate', 'IPK min 3.25', 'Surat rekomendasi'], '{"email": "beasiswa@kemdikbud.go.id", "phone": "021-5725045"}', 'https://beasiswa.kemdikbud.go.id', 'https://beasiswa.kemdikbud.go.id/unggulan', ARRAY['beasiswa', 'kemendikbud', 'unggulan'], true),

('Beasiswa BCA Finance Scholarship 2025', 'Bantuan biaya pendidikan untuk mahasiswa D3/S1 di bidang ekonomi, akuntansi, dan keuangan', 'SCHOLARSHIP', 'scholarship', '2025-05-20'::timestamp, '2025-03-01'::timestamp, '2025-05-20'::timestamp, 'BCA Finance', 'Indonesia', ARRAY['Mahasiswa aktif D3/S1', 'IPK min 3.0', 'Bidang ekonomi/akuntansi'], '{"email": "scholarship@bcafinance.co.id", "phone": "021-2358888"}', 'https://bcafinance.co.id', 'https://bcafinance.co.id/scholarship', ARRAY['beasiswa', 'BCA', 'keuangan'], true),

('Beasiswa Tanoto Foundation 2025', 'Program beasiswa dan pengembangan kepemimpinan untuk mahasiswa berprestasi dari keluarga kurang mampu', 'SCHOLARSHIP', 'scholarship', '2025-06-10'::timestamp, '2025-04-01'::timestamp, '2025-06-10'::timestamp, 'Tanoto Foundation', 'Indonesia', ARRAY['Mahasiswa aktif S1', 'IPK min 3.0', 'Kondisi ekonomi kurang mampu'], '{"email": "scholarship@tanoto.org", "phone": "021-50995999"}', 'https://tanotofoundation.org', 'https://tanotofoundation.org/id/beasiswa', ARRAY['beasiswa', 'tanoto', 'leadership'], true),

('Beasiswa Djarum Plus 2025', 'Beasiswa prestasi untuk mendukung mahasiswa aktif S1 semester 4-8 dengan prestasi akademik dan non-akademik', 'SCHOLARSHIP', 'scholarship', '2025-04-15'::timestamp, '2025-02-15'::timestamp, '2025-04-15'::timestamp, 'Djarum Foundation', 'Indonesia', ARRAY['Mahasiswa aktif S1 semester 4-8', 'IPK min 3.0', 'Prestasi non-akademik'], '{"email": "beasiswa@djarumfoundation.org", "phone": "021-5794726"}', 'https://djarumbeasiswaplus.org', 'https://djarumbeasiswaplus.org', ARRAY['beasiswa', 'djarum', 'prestasi'], true),

-- COMPETITIONS (Kompetisi)
('Kompetisi Data Science Indonesia 2025', 'Kompetisi analisis data terbesar di Indonesia dengan hadiah total 500 juta rupiah dan kesempatan magang', 'COMPETITION', 'competition', '2025-07-30'::timestamp, '2025-05-01'::timestamp, '2025-07-15'::timestamp, 'Dicoding & Google', 'Online', ARRAY['Mahasiswa/Fresh graduate', 'Pengalaman data science', 'Tim 2-4 orang'], '{"email": "datasciencecomp@dicoding.com", "phone": "021-50998877"}', 'https://dicoding.com', 'https://dicoding.com/competitions/data-science', ARRAY['kompetisi', 'data science', 'AI'], true),

('Lomba Karya Tulis Ilmiah Nasional 2025', 'Kompetisi penulisan karya ilmiah tingkat nasional untuk mahasiswa dengan tema inovasi dan teknologi', 'COMPETITION', 'competition', '2025-06-30'::timestamp, '2025-04-01'::timestamp, '2025-06-15'::timestamp, 'Kemristekdikti', 'Nasional', ARRAY['Mahasiswa aktif S1/D4', 'Karya original', 'Dosen pembimbing'], '{"email": "lktin@ristekdikti.go.id", "phone": "021-5711144"}', 'https://ristekdikti.go.id', 'https://ristekdikti.go.id/lktin', ARRAY['lomba', 'karya tulis', 'ilmiah'], true),

('Olimpiade Sains Nasional 2025', 'Kompetisi sains tingkat nasional untuk siswa SMA dalam bidang matematika, fisika, kimia, dan biologi', 'COMPETITION', 'competition', '2025-08-15'::timestamp, '2025-06-01'::timestamp, '2025-07-30'::timestamp, 'Kemendikbud', 'Jakarta', ARRAY['Siswa SMA kelas X-XII', 'Prestasi akademik', 'Rekomendasi sekolah'], '{"email": "osn@kemdikbud.go.id", "phone": "021-5725045"}', 'https://pusatprestasinasional.kemdikbud.go.id', 'https://pusatprestasinasional.kemdikbud.go.id/osn', ARRAY['olimpiade', 'sains', 'nasional'], true),

('Hackathon Fintech Indonesia 2025', 'Kompetisi pengembangan aplikasi fintech 48 jam dengan tema financial inclusion dan digital payment', 'COMPETITION', 'competition', '2025-09-20'::timestamp, '2025-07-01'::timestamp, '2025-09-10'::timestamp, 'Bank Indonesia & OJK', 'Jakarta', ARRAY['Developer/Programmer', 'Tim 3-5 orang', 'Ide fintech original'], '{"email": "hackathon@bi.go.id", "phone": "021-3818008"}', 'https://bi.go.id', 'https://bi.go.id/hackathon-fintech', ARRAY['hackathon', 'fintech', 'programming'], true),

('Kompetisi Business Plan Startup 2025', 'Lomba rencana bisnis untuk startup dengan mentoring dari investor dan entrepreneurs terkemuka', 'COMPETITION', 'competition', '2025-05-25'::timestamp, '2025-03-15'::timestamp, '2025-05-10'::timestamp, 'Startup Indonesia', 'Online & Jakarta', ARRAY['Tim 2-4 orang', 'Business plan lengkap', 'Pitch deck'], '{"email": "competition@startup.id", "phone": "021-29267888"}', 'https://startup.id', 'https://startup.id/business-plan-comp', ARRAY['business plan', 'startup', 'entrepreneur'], true),

-- INTERNSHIPS (Magang)
('Internship Program - Product Manager GoTo', 'Program magang 6 bulan sebagai Product Manager dengan mentorship langsung dari senior PM dan project real', 'INTERNSHIP', 'internship', '2025-03-30'::timestamp, '2025-02-01'::timestamp, '2025-03-15'::timestamp, 'GoTo Group', 'Jakarta', ARRAY['Mahasiswa S1 semester 6-8', 'Pengalaman project management', 'Problem solving skills'], '{"email": "internship@goto.com", "phone": "021-50881234"}', 'https://goto.com', 'https://goto.com/careers/internship', ARRAY['magang', 'product manager', 'tech'], true),

('Software Engineer Intern - Shopee', 'Kesempatan magang 3-6 bulan di tim engineering Shopee dengan proyek pengembangan aplikasi mobile dan web', 'INTERNSHIP', 'internship', '2025-04-20'::timestamp, '2025-03-01'::timestamp, '2025-04-10'::timestamp, 'Shopee Indonesia', 'Jakarta', ARRAY['Mahasiswa Teknik Informatika/SI', 'Programming skills (Java/Python/JS)', 'Portfolio project'], '{"email": "internship@shopee.co.id", "phone": "021-50998800"}', 'https://shopee.co.id', 'https://careers.shopee.co.id/internship', ARRAY['magang', 'software engineer', 'programming'], true),

('Digital Marketing Intern - Tokopedia', 'Program magang digital marketing dengan fokus pada growth marketing, social media, dan campaign management', 'INTERNSHIP', 'internship', '2025-05-15'::timestamp, '2025-04-01'::timestamp, '2025-05-05'::timestamp, 'Tokopedia', 'Jakarta', ARRAY['Mahasiswa Marketing/Komunikasi', 'Social media savvy', 'Kreatif dan analitis'], '{"email": "internship@tokopedia.com", "phone": "021-50887700"}', 'https://tokopedia.com', 'https://tokopedia.com/careers/internship', ARRAY['magang', 'digital marketing', 'social media'], true),

('Data Analyst Intern - Traveloka', 'Magang sebagai data analyst dengan pembelajaran machine learning, business intelligence, dan data visualization', 'INTERNSHIP', 'internship', '2025-06-20'::timestamp, '2025-05-01'::timestamp, '2025-06-10'::timestamp, 'Traveloka', 'Jakarta', ARRAY['Mahasiswa Matematika/Statistik/TI', 'SQL dan Python/R', 'Analytical thinking'], '{"email": "internship@traveloka.com", "phone": "021-50779900"}', 'https://traveloka.com', 'https://traveloka.com/careers/internship', ARRAY['magang', 'data analyst', 'analytics'], true),

('UI/UX Designer Intern - Bukalapak', 'Program magang desain UI/UX dengan mentorship dari senior designer dan involvement dalam project redesign', 'INTERNSHIP', 'internship', '2025-04-10'::timestamp, '2025-02-15'::timestamp, '2025-03-30'::timestamp, 'Bukalapak', 'Jakarta', ARRAY['Mahasiswa DKV/Desain', 'Portfolio design', 'Figma/Sketch skills'], '{"email": "internship@bukalapak.com", "phone": "021-50665500"}', 'https://bukalapak.com', 'https://bukalapak.com/careers/internship', ARRAY['magang', 'UI UX', 'design'], true),

-- JOB OPPORTUNITIES (Lowongan Kerja)
('Fresh Graduate Program - Bank Mandiri', 'Program pengembangan fresh graduate untuk posisi analyst, relationship manager, dan IT developer', 'JOB', 'job', '2025-05-30'::timestamp, '2025-04-01'::timestamp, '2025-05-20'::timestamp, 'Bank Mandiri', 'Seluruh Indonesia', ARRAY['Fresh graduate S1', 'IPK min 3.0', 'Tes psikologi dan wawancara'], '{"email": "recruitment@bankmandiri.co.id", "phone": "021-52997777"}', 'https://bankmandiri.co.id', 'https://bankmandiri.co.id/careers', ARRAY['kerja', 'fresh graduate', 'banking'], true),

('Junior Software Developer - Blibli', 'Posisi software developer untuk fresh graduate dengan training program komprehensif selama 6 bulan', 'JOB', 'job', '2025-06-15'::timestamp, '2025-05-01'::timestamp, '2025-06-05'::timestamp, 'Blibli.com', 'Jakarta', ARRAY['Fresh graduate Teknik Informatika', 'Programming skills', 'Familiar dengan framework modern'], '{"email": "recruitment@blibli.com", "phone": "021-50778800"}', 'https://blibli.com', 'https://blibli.com/careers', ARRAY['kerja', 'software developer', 'programming'], true),

('Management Trainee - Unilever Indonesia', 'Program management trainee 18 bulan dengan rotasi di berbagai divisi dan mentorship dari senior leader', 'JOB', 'job', '2025-04-25'::timestamp, '2025-03-01'::timestamp, '2025-04-15'::timestamp, 'Unilever Indonesia', 'Jakarta & Surabaya', ARRAY['Fresh graduate S1', 'Leadership potential', 'English proficiency'], '{"email": "recruitment.indonesia@unilever.com", "phone": "021-2358888"}', 'https://unilever.co.id', 'https://unilever.co.id/careers', ARRAY['kerja', 'management trainee', 'FMCG'], true),

('Digital Marketing Specialist - Grab', 'Posisi marketing specialist untuk mengelola digital campaign, content marketing, dan brand partnership', 'JOB', 'job', '2025-07-10'::timestamp, '2025-06-01'::timestamp, '2025-06-30'::timestamp, 'Grab Indonesia', 'Jakarta', ARRAY['1-2 tahun pengalaman marketing', 'Digital marketing knowledge', 'Creative dan data-driven'], '{"email": "recruitment@grab.com", "phone": "021-50666600"}', 'https://grab.com', 'https://grab.com/id/careers', ARRAY['kerja', 'digital marketing', 'tech company'], true),

('Financial Analyst - Astra International', 'Posisi financial analyst untuk mendukung business planning, budgeting, dan financial reporting', 'JOB', 'job', '2025-05-05'::timestamp, '2025-03-15'::timestamp, '2025-04-25'::timestamp, 'Astra International', 'Jakarta', ARRAY['S1 Akuntansi/Keuangan', 'Excel advanced', 'Analytical skills'], '{"email": "recruitment@astra.co.id", "phone": "021-65852222"}', 'https://astra.co.id', 'https://astra.co.id/careers', ARRAY['kerja', 'financial analyst', 'finance'], true),

-- CONFERENCES & EVENTS (Konferensi)
('Indonesia Tech Summit 2025', 'Konferensi teknologi terbesar di Indonesia dengan pembicara internasional dan startup showcase', 'CONFERENCE', 'conference', '2025-09-15'::timestamp, '2025-07-01'::timestamp, '2025-09-01'::timestamp, 'TechInAsia Indonesia', 'Jakarta Convention Center', ARRAY['Profesional tech', 'Mahasiswa IT', 'Entrepreneur'], '{"email": "summit@techinasia.com", "phone": "021-50999888"}', 'https://techinasia.com', 'https://events.techinasia.com/indonesia-summit', ARRAY['conference', 'technology', 'startup'], true),

('Digital Marketing Conference 2025', 'Konferensi pemasaran digital dengan workshop praktis dan networking session dengan marketing leader', 'CONFERENCE', 'conference', '2025-08-20'::timestamp, '2025-06-15'::timestamp, '2025-08-10'::timestamp, 'Indonesia Digital Marketing', 'Bali International Convention', ARRAY['Marketing professional', 'Business owner', 'Digital enthusiast'], '{"email": "conference@idm.id", "phone": "0361-123456"}', 'https://digitalmarketing.id', 'https://digitalmarketing.id/conference', ARRAY['conference', 'marketing', 'digital'], true),

('Startup Funding Summit 2025', 'Event networking untuk startup dan investor dengan pitch session dan panel discussion tentang funding', 'CONFERENCE', 'conference', '2025-10-12'::timestamp, '2025-08-01'::timestamp, '2025-10-01'::timestamp, 'Indonesia Startup Ecosystem', 'Surabaya', ARRAY['Startup founder', 'Investor', 'Entrepreneur'], '{"email": "summit@startupeco.id", "phone": "031-123456"}', 'https://startupecosystem.id', 'https://startupecosystem.id/funding-summit', ARRAY['conference', 'startup', 'funding'], true),

-- ADDITIONAL SCHOLARSHIPS
('Beasiswa Baznas 2025', 'Program beasiswa untuk mahasiswa kurang mampu dari keluarga mustahik dengan pembinaan karakter', 'SCHOLARSHIP', 'scholarship', '2025-07-20'::timestamp, '2025-05-01'::timestamp, '2025-07-10'::timestamp, 'BAZNAS', 'Indonesia', ARRAY['Mahasiswa aktif', 'Keluarga mustahik', 'Surat keterangan tidak mampu'], '{"email": "beasiswa@baznas.go.id", "phone": "021-3913777"}', 'https://baznas.go.id', 'https://baznas.go.id/beasiswa', ARRAY['beasiswa', 'baznas', 'sosial'], true),

('Beasiswa Bank Indonesia 2025', 'Beasiswa untuk mahasiswa S1/S2 bidang ekonomi dan keuangan dengan program magang di Bank Indonesia', 'SCHOLARSHIP', 'scholarship', '2025-06-05'::timestamp, '2025-04-15'::timestamp, '2025-05-25'::timestamp, 'Bank Indonesia', 'Indonesia', ARRAY['Mahasiswa Ekonomi/Keuangan', 'IPK min 3.25', 'Komitmen berkontribusi'], '{"email": "beasiswa@bi.go.id", "phone": "021-3818008"}', 'https://bi.go.id', 'https://bi.go.id/beasiswa', ARRAY['beasiswa', 'bank indonesia', 'ekonomi'], true),

-- ADDITIONAL COMPETITIONS
('Lomba Fotografi Pariwisata Indonesia 2025', 'Kompetisi fotografi dengan tema keindahan wisata Indonesia untuk mempromosikan destinasi lokal', 'COMPETITION', 'competition', '2025-08-31'::timestamp, '2025-06-01'::timestamp, '2025-08-20'::timestamp, 'Kemenparekraf', 'Nasional', ARRAY['Fotografer amatir/profesional', 'Foto original', 'Tema pariwisata Indonesia'], '{"email": "lomba@kemenparekraf.go.id", "phone": "021-3838167"}', 'https://kemenparekraf.go.id', 'https://kemenparekraf.go.id/lomba-foto', ARRAY['lomba', 'fotografi', 'pariwisata'], true),

('Kompetisi Video Kreatif TikTok 2025', 'Lomba membuat video kreatif di TikTok dengan tema edukasi dan literasi digital untuk generasi muda', 'COMPETITION', 'competition', '2025-07-25'::timestamp, '2025-05-15'::timestamp, '2025-07-15'::timestamp, 'Kominfo & TikTok', 'Online', ARRAY['Content creator', 'Video original', 'Durasi max 3 menit'], '{"email": "kompetisi@kominfo.go.id", "phone": "021-3504004"}', 'https://kominfo.go.id', 'https://kominfo.go.id/kompetisi-tiktok', ARRAY['kompetisi', 'video', 'tiktok'], true),

-- ADDITIONAL INTERNSHIPS
('Business Development Intern - Gojek', 'Magang business development dengan fokus pada partnership strategy dan market expansion', 'INTERNSHIP', 'internship', '2025-03-25'::timestamp, '2025-02-10'::timestamp, '2025-03-15'::timestamp, 'Gojek', 'Jakarta', ARRAY['Mahasiswa Bisnis/Ekonomi', 'Analytical skills', 'Presentation skills'], '{"email": "internship@gojek.com", "phone": "021-50997788"}', 'https://gojek.com', 'https://gojek.com/careers/internship', ARRAY['magang', 'business development', 'gojek'], true),

('Content Creator Intern - Kompas Gramedia', 'Program magang content creation untuk platform digital dengan pembelajaran multimedia production', 'INTERNSHIP', 'internship', '2025-04-30'::timestamp, '2025-03-15'::timestamp, '2025-04-20'::timestamp, 'Kompas Gramedia', 'Jakarta', ARRAY['Mahasiswa Komunikasi/Jurnalistik', 'Writing skills', 'Social media knowledge'], '{"email": "internship@kompasgramedia.com", "phone": "021-5347710"}', 'https://kompasgramedia.com', 'https://kompasgramedia.com/careers', ARRAY['magang', 'content creator', 'media'], true),

-- ADDITIONAL JOBS
('Cyber Security Analyst - Telkom Indonesia', 'Posisi analyst keamanan siber untuk melindungi infrastruktur digital dan sistem informasi perusahaan', 'JOB', 'job', '2025-06-25'::timestamp, '2025-05-10'::timestamp, '2025-06-15'::timestamp, 'Telkom Indonesia', 'Jakarta & Bandung', ARRAY['S1 Teknik Informatika/SI', 'Sertifikasi security (plus)', 'Problem solving skills'], '{"email": "recruitment@telkom.co.id", "phone": "021-52961161"}', 'https://telkom.co.id', 'https://telkom.co.id/careers', ARRAY['kerja', 'cyber security', 'IT'], true),

('HR Business Partner - Indofood', 'Posisi HR business partner untuk mendukung strategic HR initiatives dan employee development program', 'JOB', 'job', '2025-05-18'::timestamp, '2025-04-05'::timestamp, '2025-05-10'::timestamp, 'Indofood', 'Jakarta', ARRAY['S1 Psikologi/Manajemen', '2-3 tahun pengalaman HR', 'Communication skills'], '{"email": "recruitment@indofood.co.id", "phone": "021-65852222"}', 'https://indofood.co.id', 'https://indofood.co.id/careers', ARRAY['kerja', 'HR', 'human resources'], true),

('Supply Chain Analyst - Pertamina', 'Analyst supply chain untuk optimasi procurement, inventory management, dan distribution network', 'JOB', 'job', '2025-07-05'::timestamp, '2025-05-20'::timestamp, '2025-06-25'::timestamp, 'Pertamina', 'Jakarta', ARRAY['S1 Teknik Industri/Logistik', 'Supply chain knowledge', 'Data analysis skills'], '{"email": "recruitment@pertamina.com", "phone": "021-3815946"}', 'https://pertamina.com', 'https://pertamina.com/careers', ARRAY['kerja', 'supply chain', 'oil gas'], true);