// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doogbcrodipaeahgbjuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvb2diY3JvZGlwYWVhaGdianVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTQ3MDQsImV4cCI6MjA3MDg5MDcwNH0.ZzmotEKpgT_zdsfbZZHIq-hD54x-uJlH-fSXlQMnwdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});